quote step names in GHA YML files

diff --git a/.github/workflows/tag-release.yml b/.github/workflows/tag-release.yml
--- a/.github/workflows/tag-release.yml
+++ b/.github/workflows/tag-release.yml
@@ -25,8 +25,8 @@ on:
 
 jobs:
   tag-release:
-    name: pbt tag; git push
-    if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
+    name: "On merge: pbt tag; git push"
+    if: ${{ github.event.pull_request.merged }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -36,22 +36,20 @@ jobs:
           # token: ${{ secrets.GIT_ACCESS_TOKEN }} # pending approval
           token: ${{ secrets.VERSION_BUMPER_TOKEN }}
           fetch-tags: true
-      - name: Setup Python
+      - name: "Setup Python, `pipenv`, `pbt`, etc."
         uses: actions/setup-python@v5.5.0
         id: setup
         with:
           python-version-file: '.tool-versions'
           cache: 'pipenv'
-      - name: Install `pipenv`; `pipenv install`
+      # - name: Install `pipenv`; `pipenv install`
         run: |
           pip install 'pipenv==v2024.4.1' --user
           pipenv install
-      - run: |
+      # - run: |
           echo -n "Setup cache hit? : "
           echo ${{ steps.setup.outputs.cache-hit }}
-      - name: If `pbt --check-sync` then `pbt tag`
-        # env:
-        #   GH_TOKEN: ${{ github.token }} # for GH CLI
+      - name: "If `pbt --check-sync` then `pbt tag`"
         run: |
           if pipenv run \
             pbt versioning \
@@ -73,5 +71,6 @@ jobs:
               echo "Pushed new tag `$(git tag --contains)` onto branch `$GITHUB_REF_NAME`"
           else
               echo "`pbt versioning --sync-check` failed; please check Prophecy metadata"
-              exit 1  # Fail the job to indicate changes were needed
+              # Fail the job to indicate changes were needed
+              exit 1
           fi
